export const coffeeMenu = [
    {
      id: 'cappuccino',
      name: 'Cappuccino',
      image: require('@/assets/images/cappuccino.jpg'),
      description: 'Rich espresso with steamed milk and a light layer of foam.',
      origin: 'Italy',
      strength: 3,
      temperature: 'Hot',
      flavors: ['Milky', 'Creamy'],
    },
    {
      id: 'iced-latte',
      name: 'Iced Latte',
      image: require('@/assets/images/iced-latte.jpg'),
      description: 'Chilled milk with espresso over ice.',
      origin: 'USA',
      strength: 2,
      temperature: 'Iced',
      flavors: ['Smooth', 'Refreshing'],
    },
    {
      id: 'espresso',
      name: 'Espresso',
      image: require('@/assets/images/espresso.jpg'),
      description: 'Strong, black coffee made by forcing steam through ground coffee beans.',
      origin: 'Italy',
      strength: 5,
      temperature: 'Hot',
      flavors: ['Bold', 'Rich'],
    },
    {
      id: 'mocha',
      name: 'Mocha',
      image: require('@/assets/images/mocha.jpg'),
      description: 'A mix of espresso, steamed milk, and chocolate syrup.',
      origin: 'Yemen',
      strength: 3,
      temperature: 'Hot',
      flavors: ['Chocolatey', 'Sweet'],
    },
    {
      id: 'cold-brew',
      name: 'Cold Brew',
      image: require('@/assets/images/coffe.jpg'),
      description: 'Coffee brewed slowly in cold water, served chilled.',
      origin: 'Japan',
      strength: 4,
      temperature: 'Iced',
      flavors: ['Smooth', 'Bold'],
    },
    {
      id: 'flat-white',
      name: 'Flat White',
      image: require('@/assets/images/iced-latte.jpg'),
      description: 'Espresso with microfoam, silky and balanced.',
      origin: 'Australia',
      strength: 3,
      temperature: 'Hot',
      flavors: ['Velvety', 'Balanced'],
    },
    {
      id: 'affogato',
      name: 'Affogato',
      image: require('@/assets/images/espresso.jpg'),
      description: 'Espresso poured over a scoop of vanilla ice cream.',
      origin: 'Italy',
      strength: 4,
      temperature: 'Hot + Cold',
      flavors: ['Sweet', 'Creamy'],
    },
    {
      id: 'macchiato',
      name: 'Macchiato',
      image: require('@/assets/images/iced-coffee.jpg'),
      description: 'Espresso with a dash of steamed milk.',
      origin: 'Italy',
      strength: 4,
      temperature: 'Hot',
      flavors: ['Strong', 'Slightly creamy'],
    },
    {
      id: 'frappe',
      name: 'Frappe',
      image: require('@/assets/images/cappuccino.jpg'),
      description: 'Blended iced coffee with milk and sweetener.',
      origin: 'Greece',
      strength: 2,
      temperature: 'Iced',
      flavors: ['Sweet', 'Refreshing'],
    },
    {
      id: 'americano',
      name: 'Americano',
      image: require('@/assets/images/espresso.jpg'),
      description: 'Espresso diluted with hot water, smooth and bold.',
      origin: 'USA',
      strength: 3,
      temperature: 'Hot',
      flavors: ['Smooth', 'Neutral'],
    },
  ];  